### PR TITLE
Fix Grayscale Image Support

### PR DESCRIPTION
**Pull request by usert5432**
Hi @YHRen,

I have added a new cyclegan dataset with a custom image loader, which leaves the grayscale images as grayscale ones. Could I ask you please to take a quick look over the new implementation (https://github.com/LS4GAN/uvcgan/commit/328c64bae3c93b328772178dfc33abc29f819111)?

Closes: https://github.com/LS4GAN/uvcgan/issues/18

### CODE REVIEW

**Comment by usert5432** [comment]
I have run a quick BERT test (just a few epochs) with the new dataset (both grayscale and RBG). The results seem fine.
reco_color
reco_gray

**Review by YHRen — COMMENTED** [review]
Hi @usert5432 

Thanks a lot. First of all, sorry I didn't realize the `default_loader` is in torchvision although you have said so explicitly. 

The current PR should function correctly. But `load_cyclegan_v2_datasets` is too similar to the original one, this usually indicates a better design exists.  The original one will throw a warning regardless the input, this would not be a good user experience.

Please consider the following, see if it works better. The root cause is the `default_loader` provided by `torchvision`. Instead of creating `cyclegan_v2.py`, `image_loader` can be placed in `funcs.py` and used in place of the [`default_loader`](https://github.com/LS4GAN/uvcgan/blob/0bf89e04967f0951a1cb8429b4331bb0403589c0/uvcgan/data/datasets/funcs.py#L1). Will this solve the problem?

**Review by YHRen — APPROVED** [review]
@usert5432  Thanks.

**Review by YHRen — APPROVED** [review]
@usert5432  Yes. Looks great. Thank you!

**Pull request merged**
